version: "3.9"

services:

  elasticsearch:
    container_name: "raudikko-elasticsearch"
    build:
      target: elasticsearch
        # change version here or use
        # docker compose build --build-arg "ES_VERSION=<custom_version>" elasticsearch
        #args:
      #ES_VERSION: 8.5.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    # NOTE on WSL needed to adjust following
    # wsl -d docker-desktop
    # sysctl -w vm.max_map_count=262144

  opensearch:
    container_name: "raudikko-opensearch"
    build:
      target: opensearch
        # change version here or use
        # docker compose build --build-arg "OS_VERSION=<custom_version>" opensearch
        #args:
      #OS_VERSION: 2.5.0
    ports:
      - "9201:9200"
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
