version: "3.9"
services:
  elasticsearch:
    build:
      dockerfile: /etc/Dockerfile
      context: ../
      # change version here or use
      # docker compose build --build-arg "ES_VERSION=<custom_version>"
      #args:
        #ES_VERSION: 8.5.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    # NOTE on WSL needed to adjust following
    # wsl -d docker-desktop
    # sysctl -w vm.max_map_count=262144
