### test analyzer
GET localhost:9200/_analyze
Content-Type: application/json; charset=UTF-8

{
  "tokenizer" : "finnish",
  "filter" : [{"type": "raudikko"}],
  "text" : "Testataan raudikon analyysiä tällä tavalla yksinkertaisesti."
}

### check status
GET http://localhost:9200/_cluster/health?pretty

### check version
GET http://localhost:9200

### show plugins
GET http://localhost:9200/_cat/plugins?v=true&s=component&h=component,version,description